travis:
  secure:
    BINSTAR_TOKEN: QSLf+fims2J6623laciUP7Lmj+BuiqIxCb5vEe2YeE4fJxKBa24+0c28puAPAELYYjRIpomkXZkjKwpq6LcOwEdIhfJfjRk4E/QWPY0igH9l8VupUrcBLQsYX1cqPApO0my84m0M9L6+dg5qG/wMCW8LBrfJD0B2XD74xCaut+yZVkBr+EOdnGoIyHQH2uHkrn5HdUITPpX21qg1Dst/7bTSp0Zj1okVOVlzXlnpMSwHOA5wrP3n+1wDf3J/fvl6MDyJmOx5D21lZGOpXLyCBMR00E6rwH2S0DJ5YIH/TzZlHq3AFyeLs82UXWlZZkVczCo7TMZj4GsGej246PC0Tk2RsPdB+OvN4DtXwog59d0Vo1wv0Bs1JcU9sH5nQGP/+7TtLpfHNBMXlrRBy5mzXPvO1dpx6ioy8MH8ypcrbtw20j8d6Wmm1allP6Y9oE9G8+Pi9zVl+XePWQaqN4ZoGMV4IrbARjr3rq3+1G5/ZawipSuqjBKDQd8wtDqOdEb4XNWFgpnLp758T8nifATmx7nmwQXOrUts5FzpwNM78D50SAd8kepeaNDA6vPwFS32E46c5JyCqOKjHpV3CNpv0+PMUyG55vx6QQaP2m9NdtAyY4n0OZZtm6N2RnxnzTMZFEg9b+NL8EP5yUZMcRUbLPKuj/o1gNmJYFhkTeQ+n9s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
