travis:
  secure:
    BINSTAR_TOKEN: Wvpiv/Vhg3nyN1m8PcHd5Zo1FS2dVt/CFXRbMazEmqOtVmY/hIcUk3aO0v1ypY6Ts/krRS0S3XMHFBiT8z4Aa0CFIcMa0Ulyi9GwUrsv0O2L4P5gPdVzwCEaPiInR+wrJjtPINCYkgHMOeBHbpMo7UOdksma0AHMg5qm/HdFcNe7yZwpBjKqoLWoJcEyaSebZylIl69e8nQXRmq1F97nLe3clPiXesCCIvFQARzEfOERyo8t9GChYvd2C6piIge/I23J5HVdUEst1f/b7I3z2xBG+p+g6+o8XtFJwkZ1B2yjc8Q+ZNOWRpb6tEdqRwG5hxbCkcrgrLT/jm/y4SR1QByOK/I7f3ilxluSsYG4WOakXD7/wFpoGnulnVi8GP+cBp3A+9xjXxghifdkxuT1WWenH7RHTzPH+XjtKzC01FQH6LMaWwkKvqovGUS4uHT1RXnbvTmS7TWHcJZxiw2u/Qca9O0b9e/cgQ5naAFZxuegBPZg7Nq/sv5AOMiuxd+p4CmkViNJIgP5koPy39AFxUcUI2TtjyaNiRFv3Hmujchfn4N8TmtVT2E3sHNEyMIyhHmxO/G2uvoBz0PfAA51s+SYoeEL5M6BYeyj1nhwupQMnHXSh6rAtVoIiEViZu0AM1NT+h6cnxe6nH/dNxX4mvv6UFp2kN0Lqj7vaiEYm1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
