travis:
  secure:
    BINSTAR_TOKEN: wxoI9uG5otA1LLXrqjP6X2QlxdpaItE+gH08zXHCZEBqFbxEXPqBqrwaZ5FeMs7QIOezlUwUbf5sHEtk2qG870JPw7BbEujPVpHuVEXPzr3F1f5apeviU82oeaGCy7vcSDFGWnGj/IBoIfmfI9+ZLnDvvcq8Yq3nMtLchPkZESUbWrGT+YEUJJZW7lypTEZ1jrKhdEf40XpFnMBcWcJLV/KGY3mqNJna5iES4TCcfWup71fMbHIaCfCDqP3ida9hk8KDVRwF83Vr/IO/CJTH1B6gi8CAG3vwH72SHG9BZJP+M8QHeZShBip4oiVP00W1iCdDqgChXU1osTX4cvUT/DitS7JqmiBjZdEC/uDQRMpKq4+PbIjJm/QPzuBu93tDW5JgqMlut8OMUIioIRrUZFUIxx/nQVmr1XcvRw5T2qv9nc/RMlj4q+Org9cnJerVN65pWooICJXH81u6a1G+iKI9Ns2rarG4iIUE53bF7UA98JKlIdUXiQtDTwMhLGZ4Jsla2qQxz7cCmJmEEigO5cBQaTM3HfXCXVcrnvz6gEBUe69Cbklo0FqMc/X4PpePUXskdC9BCNavuUsyBAxTkAuH0899Rgjly2JrA1DP4B1x80Z7UtCGQp/i86jFmU3Xm+wqKdIvxfCKgxIHBJgnp+e59kxvzXQ6kQ6Uhx14PCc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
