appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: brPTexMoxF084K4d0V/+eBR/Lf4gkxLil0JGexyMjEGvpDzXrvqX2V7DcovZNEzfIkh63N/SM5sx9YGidJnSyRQV75JH/R5H5GJoMEJo3N8KQ9qKy35zYEn9yn5w22PV6zljcpS0knKqrkaBGRlArFp3aNdEhTy5cBKFXpgzHc01TJ6YbEcNi3+sFkT2wo+ZTbHq0XfcHW1U20g9I6Z2K/x9ureFWfUEbDgGRlfL1W7+RtB9ud+MFXrDnwgv93rjYDPMuXWvxYIJxDP7euIa+kgJd3dspGmr+Gp2nMoFry7FMFKf7b+XLyT+PEWFXE8DwHgPOe1sMjlQfAdPWPEymen6C/XR4fTEnHClYKGoLy14Ep9e19KNwiTsBHr8SNXTXXv0/HU7b8s0J2Qa2nXxcx0FTOQVDRs8ampzdiJ+QWa0IszweV5abVm+gOhqs2HQf6a46Wch6SouJscOIeERhgAJW41Om8kQAsQ/+osa50WkCiSJeKTYZXm+Q2uIA8eYVKQGMzWjuFr07Bb22h2CSlFJbCX099WI82ONcdEOanlVLzR7A+K8n4PkKi7QYl+TUuERNO5gkkZh3DwziyJLEQ3rVLKgBLV4qEfMPZtx447UolLw+g/bl62H/g0xQ5jys+ewBMKK+cvNohPRp8em+w7Z3rU1xss3yEqNZx9NxO4=}
